#!/usr/bin/expect
spawn report select.out
expect "Date TimeE L E LatE LonE Dep E F Aga Nsta Rms Gap McA MlA MbA MsA MwA Fp Spec"
send   "               x  x x  x x   x            x           x  \r"
interact
