#!/usr/bin/env python
# -*- coding: utf-8 -*-
from Tkinter import *
import tkFileDialog
import datetime
import tkMessageBox
import Tkinter
import sys
import os
import subprocess
import os, time, math, tempfile
import numpy 
from glob import glob
from time import *
from datetime import *
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib import cm

#ruta = "/home/camilo/Backup_208/camilo/read_select.208/V3_codigo/"
#ruta = "/home/camilo/TEMP/scapp/"
ruta = os.path.dirname(os.path.abspath(__file__))+"/"
#ruta = "/home/camilo/scapp/"

class Planificador(Frame):
    def __init__(self,master):
        Frame.__init__(self, master)
        self.master = master
        self.initUI()

    def initUI(self):
        self.master.title("Boletin")
        self.frameini = Frame(self.master)
        self.frameini.grid(row=0,column=0)
        self.frameOne = Frame(self.master)
        self.frameOne.grid(row=1,column=0)
	
	#parametros=glob("/home/Cmunoz/read_select/select.inp")
	#archivo=open(parametros[0],"r")
	##print "Nombre del archivo : ", archivo.name
	##print "Cerrado o no : ", archivo.closed
	##print "Modo de apertura : ", archivo.mode
	#lines=archivo.readlines()
	##print (lines[0])
	#contenido = ''
	
	self.menu_inicial()
	
############################Ventana Inicial####################################

    def menu_inicial(self):
	self.frameOne.destroy()
	self.frameini=Toplevel()

	self.vini_1,self.vini_2,self.vini_3,self.vini_4,self.vini_5, = StringVar(),StringVar(),StringVar(),StringVar(),StringVar()

	self.texto = Label(self.frameini,text="Año Boletin", width=18)
	self.texto.grid(row=0, column=0, pady=(5,5))
	self.E = Entry(self.frameini,width=14,textvariable=self.vini_1)
	self.E.grid(row=0, column=1, padx=(0,10))

	self.texto = Label(self.frameini,text="Mes Boletin", width=18)
	self.texto.grid(row=0, column=2, pady=(5,5))
	self.E = Entry(self.frameini,width=14,textvariable=self.vini_2)
	self.E.grid(row=0, column=3, padx=(0,10))

	self.texto = Label(self.frameini,text="Mes Realizacion Boletin", width=18)
	self.texto.grid(row=1, column=0, padx=(0,8))
	self.E = Entry(self.frameini,width=14,textvariable=self.vini_3)
	self.E.grid(row=1, column=1, padx=(0,10))

	self.texto = Label(self.frameini,text="Volumen", width=18)
	self.texto.grid(row=1, column=2, pady=(5,5))
	self.E = Entry(self.frameini,width=14,textvariable=self.vini_4)
	self.E.grid(row=1, column=3, padx=(0,10))

	self.texto = Label(self.frameini,text="Numero", width=18)
	self.texto.grid(row=2, column=0, pady=(5,5))
	self.E = Entry(self.frameini,width=14,textvariable=self.vini_5)
	self.E.grid(row=2, column=1, padx=(0,10))

	self.select = Button(self.frameini,text="BOLETIN", command=self.ir_boletin,width=18)
	self.select.grid(row=2, column=2, pady=(5,5))

	self.salir2=Button(self.frameini, text='Menu', command=self.quit)
	self.salir2.grid(row=2, column=3, padx=(5,5))



######################################VENTANA BOLETIN###################################
    def ir_boletin(self):
	self.frameini.destroy()
	self.frameOne=Toplevel()

	contenidoini = ''
	contenidoini += self.vini_1.get()+','+self.vini_2.get()+','+self.vini_3.get()+','+self.vini_4.get()+','+self.vini_5.get()

	archivoini= open('boletin2.inp','w')
	archivoini.write(contenidoini)
	archivoini.close
	self.Var1,self.Var2,self.Var3,self.Var4,self.Var5,self.Var2_1,self.Var2_2,self.Var2_3,self.Var3_1,self.Var3_2,self.Var3_3,self.Var3_4,self.Var4_1,self.Var4_2,self.Var4_3,self.Var4_4,self.Var5_1,self.Var5_2=IntVar(),IntVar(),IntVar(),IntVar(),IntVar(),IntVar(),IntVar(),IntVar(),IntVar(),IntVar(),IntVar(),IntVar(),IntVar(),IntVar(),IntVar(),IntVar(),IntVar(),IntVar()

	self.v5_1,self.v5_2 = IntVar(),IntVar()

	self.v2_1_1,self.v2_2_1,self.v2_3_1,self.v3_1_1,self.v3_2_1,self.v3_3_1,self.v3_4_1,self.v4_1_1,self.v4_2_1,self.v4_3_1,self.v4_4_1,self.v5_1_1,self.v5_2_1 = StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar()

	self.v2_1_2,self.v2_2_2,self.v2_3_2,self.v3_1_2,self.v3_2_2,self.v3_3_2,self.v3_4_2,self.v4_1_2,self.v4_2_2,self.v4_3_2,self.v4_4_2,self.v5_1_2,self.v5_2_2 = StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar(),StringVar()


	self.v5_1_3,self.v5_2_3=StringVar(),StringVar()

	self.v5_1.set('0')
	self.v5_2.set('0')

	self.Var1.set('1'),self.Var2.set('1'),self.Var2_2.set('1'),self.v2_2_1.set('est.png'),self.v2_2_2.set('est.dat'),self.Var2_3.set('1'),self.v2_3_1.set('func.jpg'),self.v2_3_2.set('func.dat'),self.Var3.set('1'),self.Var3_1.set('1'),self.Var3_2.set('1'),self.v3_2_1.set('dest.png'),self.v3_2_2.set('dest.dat'),self.Var3_3.set('1'),self.Var3_4.set('1'),self.v3_4_1.set('sis.png'),self.v3_4_2.set('sis.dat'),self.Var4.set('1'),self.Var4_1.set('1'),self.v4_1_2.set('errores.dat'),self.Var4_2.set('1'),self.v4_2_2.set('No_sismos.dat'),self.Var4_3.set('1'),self.v4_3_2.set('Evol_Temp.dat')


	self.texto = Label(self.frameOne, height='3', text = "SECCIONES", justify="center")
        self.texto.grid(row=0, column=2)

	self.texto = Label(self.frameOne, height='3', text = "CONTENIDOS", justify="center")
        self.texto.grid(row=0, column=4)

	self.texto = Label(self.frameOne, height='3', text = "IMAGENES", justify="center")
        self.texto.grid(row=0, column=5)

	self.texto = Label(self.frameOne, height='3', text = "TEXTO ADICIONAL", justify="center")
        self.texto.grid(row=0, column=6)

	self.check = Checkbutton(self.frameOne, variable = self.Var1, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=1, column=1)
	self.texto = Label(self.frameOne,text="Presentacion", width=18)
	self.texto.grid(row=1, column=2, pady=(5,5))

	self.check = Checkbutton(self.frameOne, variable = self.Var2, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=2, column=1)
	self.texto = Label(self.frameOne,text="Funcionamiento", width=18)
	self.texto.grid(row=2, column=2, pady=(5,5))

#	self.check = Checkbutton(self.frameOne, variable = self.Var2_1, onvalue =1, offvalue = 0, height=1, width = 5)
#	self.check.grid(row=3, column=3)
#	self.texto = Label(self.frameOne,text="Tabla Funcionamiento", width=18)
#	self.texto.grid(row=3, column=4, pady=(5,5))
#	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v2_1_1)
#	self.E1.grid(row=3, column=5, padx=(0,10))
#	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v2_1_2)
#	self.E1.grid(row=3, column=6, padx=(0,10))

	self.check = Checkbutton(self.frameOne, variable = self.Var2_2, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=4, column=3)
	self.texto = Label(self.frameOne,text="Mapa Estaciones", width=18)
	self.texto.grid(row=4, column=4, pady=(5,5))
	self.E2 = Entry(self.frameOne,width=14,textvariable=self.v2_2_1)
	self.E2.grid(row=4, column=5, padx=(0,10))
	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v2_2_2)
	self.E1.grid(row=4, column=6, padx=(0,10))

	self.check = Checkbutton(self.frameOne, variable = self.Var2_3, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=5, column=3)
	self.texto = Label(self.frameOne,text="Histograma Funcionamiento", width=22)
	self.texto.grid(row=5, column=4, pady=(5,5))
	self.E3 = Entry(self.frameOne,width=14,textvariable=self.v2_3_1)
	self.E3.grid(row=5, column=5, padx=(0,10))
	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v2_3_2)
	self.E1.grid(row=5, column=6, padx=(0,10))

	self.check = Checkbutton(self.frameOne, variable = self.Var3, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=6, column=1)
	self.texto = Label(self.frameOne,text="Sismicidad", width=18)
	self.texto.grid(row=6, column=2, pady=(5,5))

	self.check = Checkbutton(self.frameOne, variable = self.Var3_1, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=7, column=3)
	self.texto = Label(self.frameOne,text="Tabla Destacados", width=20)
	self.texto.grid(row=7, column=4, pady=(5,5))
#	self.E4 = Entry(self.frameOne,width=14,textvariable=self.v3_1_1)
#	self.E4.grid(row=7, column=5, padx=(0,10))
#	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v3_1_2)
#	self.E1.grid(row=7, column=6, padx=(0,10))

	self.check = Checkbutton(self.frameOne, variable = self.Var3_2, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=8, column=3)
	self.texto = Label(self.frameOne,text="Mapa Destacados", width=20)
	self.texto.grid(row=8, column=4, pady=(5,5))
	self.E5 = Entry(self.frameOne,width=14,textvariable=self.v3_2_1)
	self.E5.grid(row=8, column=5, padx=(0,10))
	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v3_2_2)
	self.E1.grid(row=8, column=6, padx=(0,10))

	self.check = Checkbutton(self.frameOne, variable = self.Var3_3, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=9, column=3)
	self.texto = Label(self.frameOne,text="Tabla Sismicidad", width=20)
	self.texto.grid(row=9, column=4, pady=(5,5))
#	self.E6 = Entry(self.frameOne,width=14,textvariable=self.v3_3_1)
#	self.E6.grid(row=9, column=5, padx=(0,10))
#	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v3_3_2)
#	self.E1.grid(row=9, column=6, padx=(0,10))

	self.check = Checkbutton(self.frameOne, variable = self.Var3_4, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=10, column=3)
	self.texto = Label(self.frameOne,text="Mapa Sismicidad", width=20)
	self.texto.grid(row=10, column=4, pady=(5,5))
	self.E7 = Entry(self.frameOne,width=14,textvariable=self.v3_4_1)
	self.E7.grid(row=10, column=5, padx=(0,10))
	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v3_4_2)
	self.E1.grid(row=10, column=6, padx=(0,10))

	self.check = Checkbutton(self.frameOne, variable = self.Var4, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=11, column=1)
	self.texto = Label(self.frameOne,text="Estadisticas", width=18)
	self.texto.grid(row=11, column=2, pady=(5,5))

	self.check = Checkbutton(self.frameOne, variable = self.Var4_1, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=12, column=3)
	self.texto = Label(self.frameOne,text="Errores", width=20)
	self.texto.grid(row=12, column=4, pady=(5,5))
#	self.E8 = Entry(self.frameOne,width=14,textvariable=self.v4_1_1)
#	self.E8.grid(row=12, column=5, padx=(0,10))
	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v4_1_2)
	self.E1.grid(row=12, column=6, padx=(0,10))


	self.check = Checkbutton(self.frameOne, variable = self.Var4_2, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=13, column=3)
	self.texto = Label(self.frameOne,text="No de Sismos", width=20)
	self.texto.grid(row=13, column=4, pady=(5,5))
#	self.E9 = Entry(self.frameOne,width=14,textvariable=self.v4_2_1)
#	self.E9.grid(row=13, column=5, padx=(0,10))
	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v4_2_2)
	self.E1.grid(row=13, column=6, padx=(0,10))

	self.check = Checkbutton(self.frameOne, variable = self.Var4_3, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=14, column=3)
	self.texto = Label(self.frameOne,text="Evolucion Temporal", width=20)
	self.texto.grid(row=14, column=4, pady=(5,5))
#	self.E9 = Entry(self.frameOne,width=14,textvariable=self.v4_3_1)
#	self.E9.grid(row=14, column=5, padx=(0,10))
	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v4_3_2)
	self.E1.grid(row=14, column=6, padx=(0,10))


	self.check = Checkbutton(self.frameOne, variable = self.Var4_4, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=15, column=3)
	self.texto = Label(self.frameOne,text="Extras", width=20)
	self.texto.grid(row=15, column=4, pady=(5,5))
#	self.E10 = Entry(self.frameOne,width=14,textvariable=self.v4_4_1)
#	self.E10.grid(row=15, column=5, padx=(0,10))
	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v4_4_2)
	self.E1.grid(row=15, column=6, padx=(0,10))

	self.check = Checkbutton(self.frameOne, variable = self.Var5, onvalue =1, offvalue = 0, height=1, width = 5)
	self.check.grid(row=16, column=1)
	self.texto = Label(self.frameOne,text="Sismicidad Especial", width=18)
	self.texto.grid(row=16, column=2, pady=(5,5))


#	self.check = Checkbutton(self.frameOne, variable = self.Var5_1, onvalue =1, offvalue = 0, height=1, width = 5)
#	self.check.grid(row=17, column=2)
	self.textopieza = Label(self.frameOne, text = "Imagenes", justify="left")
        self.textopieza.grid(row=17, column=3)
	self.O1 = OptionMenu(self.frameOne,self.v5_1,'0','1','2','3')
	self.O1.grid(row=18, column=3, padx=(0,20))
	self.E10 = Entry(self.frameOne,width=14,textvariable=self.v5_1_1)
	self.E10.grid(row=17, column=5, padx=(0,10))
	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v5_1_2)
	self.E1.grid(row=18, column=5, padx=(0,10))
	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v5_1_3)
	self.E1.grid(row=19, column=5, padx=(0,10))


#	self.check = Checkbutton(self.frameOne, variable = self.Var5_2, onvalue =1, offvalue = 0, height=1, width = 5)
#	self.check.grid(row=18, column=2)
	self.textopieza = Label(self.frameOne, text = "Texto", justify="left")
        self.textopieza.grid(row=17, column=4)
	self.O2 = OptionMenu(self.frameOne,self.v5_2,'0','1','2','3')
	self.O2.grid(row=18, column=4, padx=(0,20))
	self.E10 = Entry(self.frameOne,width=14,textvariable=self.v5_2_1)
	self.E10.grid(row=17, column=6, padx=(0,10))
	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v5_2_2)
	self.E1.grid(row=18, column=6, padx=(0,10))
	self.E1 = Entry(self.frameOne,width=14,textvariable=self.v5_2_3)
	self.E1.grid(row=19, column=6, padx=(0,10))

	self.ayuda1 = Label(self.frameOne, text = "Ayuda", justify="left")
	self.ayuda1.grid(row=1, column=5)

	self.ayuda2 = Label(self.frameOne, text = "Ayuda", justify="left")
	self.ayuda2.grid(row=1, column=6)

	self.ayuda3 = Label(self.frameOne, text = "Ayuda", justify="left")
	self.ayuda3.grid(row=16, column=5)

	self.ayuda4 = Label(self.frameOne, text = "Ayuda", justify="left")
	self.ayuda4.grid(row=16, column=6)

	def showMenu1(e):
		menu1.post(e.x_root, e.y_root)
	def showMenu2(e):
		menu2.post(e.x_root, e.y_root)
	def showMenu3(e):
		menu3.post(e.x_root, e.y_root)
	def showMenu4(e):
		menu4.post(e.x_root, e.y_root)

	menu1 = Menu(self.frameOne, tearoff=0)
	menu1.add_command(label="Escribir el nombre del archivo con la imagen correspondiente")
	menu1.add_command(label="a cada contenido, el archivo debe estar en la carpeta local.")
	menu1.add_command(label="Este contenido es Obligatorio.")

	menu2 = Menu(self.frameOne, tearoff=0)
	menu2.add_command(label="Escribir el nombre del archivo con el texto plano correspondiente")
	menu2.add_command(label="a cada contenido, el archivo debe estar en la carpeta local.")
	menu2.add_command(label="Este contenido es opcional.")

	menu3 = Menu(self.frameOne, tearoff=0)
	menu3.add_command(label="Escribir los nombres de las imagenes correspondientes,")
	menu3.add_command(label="el numero de imagenes seleccionadas debe coincidir con")
	menu3.add_command(label="el numero de nombres ingresados.")

	menu4 = Menu(self.frameOne, tearoff=0)
	menu4.add_command(label="Escribir los nombres de los archivos con texto plano,")
	menu4.add_command(label="el numero de archivos seleccionados debe coincidir con")
	menu4.add_command(label="el numero de nombres ingresados.")

	self.ayuda1.bind("<Enter>", showMenu1)
	self.ayuda2.bind("<Enter>", showMenu2)
	self.ayuda3.bind("<Enter>", showMenu3)
	self.ayuda4.bind("<Enter>", showMenu4)

	self.salir2=Button(self.frameOne, text='Cargar_Configuracion', command=self.cargar)
	self.salir2.grid(row=20, column=1, padx=(5,5))

	self.salir2=Button(self.frameOne, text='Hacer_Boletin', command=self.make)
	self.salir2.grid(row=20, column=2, padx=(5,5))

	self.salir2=Button(self.frameOne, text='Ver_Boletin', command=self.ver)
	self.salir2.grid(row=20, column=3, padx=(5,5))

	self.salir2=Button(self.frameOne, text='Archivo_.tex')
	self.salir2.grid(row=20, column=4, padx=(5,5))

	self.salir2=Button(self.frameOne, text='Menu', command=self.quit)
	self.salir2.grid(row=20, column=6, padx=(5,5))

############Linea###############################

	self.c1 = Canvas(self.frameOne, width=800, height=5, bg='#DCDCDC')
	self.c1.grid(row=2, column=0, columnspan = 7, sticky=N)
	self.c1.create_line(3, 3, 800, 3,width=1)

	self.c1 = Canvas(self.frameOne, width=800, height=5, bg='#DCDCDC')
	self.c1.grid(row=6, column=0, columnspan = 7, sticky=N)
	self.c1.create_line(3, 3, 800, 3,width=1)

	self.c1 = Canvas(self.frameOne, width=800, height=5, bg='#DCDCDC')
	self.c1.grid(row=11, column=0, columnspan = 7, sticky=N)
	self.c1.create_line(3, 3, 800, 3,width=1)

	self.c1 = Canvas(self.frameOne, width=800, height=5, bg='#DCDCDC')
	self.c1.grid(row=16, column=0, columnspan = 7, sticky=N)
	self.c1.create_line(3, 3, 800, 3,width=1)

###########Logo###############################
	self.c1 = Canvas(self.frameOne, width=150, height=60, bg='#DCDCDC')
	self.ima1 = PhotoImage(file=ruta+'Logo-SGC3.gif')
	self.c1.grid(row=0, column=3, rowspan = 4, sticky=W+N, pady=0)
	self.c1.create_image((0,0), image=self.ima1,anchor=NW)


    def cargar(self):
	contenido1 = ''
#	contenido1 += str(self.Var1)+'\n'+str(self.Var2)+'\n'+str(self.Var2_1)+'\n'+str(v2_1_1)+'\n'+str(self.Var2_2)+'\n'+str(v2_2_1)+'\n'+str(self.Var2_3)+'\n'+str(v2_3_1)+'\n'+str(self.Var3)+'\n'+str(self.Var3_1)+'\n'+str(v3_1_1)+'\n'+str(self.Var3_2)+'\n'+str(self.Var3_3)+'\n'+str(self.Var3_4)+'\n'+str(self.Var4)+'\n'+str(self.Var4_1)+'\n'+str(self.Var4_2)+'\n'+str(self.Var4_3)+'\n'+str(self.Var4_4)+'\n'+str(self.Var5)+'\n'+str(self.Var5_1)+'\n'+str(self.Var5_2)


	contenido1 += str(self.Var1.get())+'\n' \
		      +str(self.Var2.get())+'\n' \
		      +str(self.Var2_1.get())+','+str(self.v2_1_1.get())+','+str(self.v2_1_2.get())+'\n' \
		      +str(self.Var2_2.get())+','+str(self.v2_2_1.get())+','+str(self.v2_2_2.get())+'\n' \
		      +str(self.Var2_3.get())+','+str(self.v2_3_1.get())+','+str(self.v2_3_2.get())+'\n' \
		      +str(self.Var3.get())+'\n' \
		      +str(self.Var3_1.get())+','+str(self.v3_1_1.get())+','+str(self.v3_1_2.get())+'\n' \
		      +str(self.Var3_2.get())+','+str(self.v3_2_1.get())+','+str(self.v3_2_2.get())+'\n' \
		      +str(self.Var3_3.get())+','+str(self.v3_3_1.get())+','+str(self.v3_3_2.get())+'\n' \
		      +str(self.Var3_4.get())+','+str(self.v3_4_1.get())+','+str(self.v3_4_2.get())+'\n' \
		      +str(self.Var4.get())+'\n' \
		      +str(self.Var4_1.get())+','+str(self.v4_1_1.get())+','+str(self.v4_1_2.get())+'\n' \
		      +str(self.Var4_2.get())+','+str(self.v4_2_1.get())+','+str(self.v4_2_2.get())+'\n' \
		      +str(self.Var4_3.get())+','+str(self.v4_3_1.get())+','+str(self.v4_3_2.get())+'\n' \
		      +str(self.Var4_4.get())+','+str(self.v4_4_1.get())+','+str(self.v4_4_2.get())+'\n' \
		      +str(self.Var5.get())+'\n' \
		      +str(self.v5_1.get())+','+str(self.v5_1_1.get())+','+str(self.v5_1_2.get())+','+str(self.v5_1_3.get())+'\n' \
		      +str(self.v5_2.get())+','+str(self.v5_2_1.get())+','+str(self.v5_2_2.get())+','+str(self.v5_2_3.get())

	archivo1= open('boletin.inp','w')
	archivo1.write(contenido1)
	archivo1.close

	print "Se ha generado el archivo boletin.inp"

    def make(self):
	os.system(ruta+"./main_latex.py")
	os.system("mkdir data_bullet")
	os.system("mv b_201803.tex b_201803.aux b_201803.toc b_201803.ptc b_201803.out b_201803.fls b_201803.log b_201803.fdb_latexmk data_bullet")

    def ver(self):
	os.system("okular b*.pdf")



######################################################################################

if __name__ == "__main__":
    	root = Tk()
    	aplicacion = Planificador(root)
	root.mainloop()














